### PR TITLE
Update for NodeBB 2.0

### PR DESCRIPTION
**Pull request by oplik0**
This PR constists of 2 parts:
1. update to plugin.json moving scripts and acpScripts to modules (and package.json to update compatibility)
2. removal of icon replacement script from #9 - since FontAwesome 5 is now available in NodeBB (and the icon was updated in #13) it shouldn't be needed anymore

EDIT: It appears that there was an issue I missed with FontAwesome 5 brands font - the `.fab` class conflicts with some floating action button from somewhere (possibly Bootstrap), which doesn't work great here... As such to make the icon work properly (without being put in a circle) I just added a replacement class here (`.fa-brands`). I'll also think about how to resolve this NodeBB-wide, since it seems a bit silly.

EDIT 2: this was fixed in https://github.com/NodeBB/nodebb-theme-persona/commit/610d5bfe6df0cf422e756793dc55d9ea26d56842 - so not sure if I should leave the workaround with less for now or update compatibility to v2.2.0 and up. I also updated the workaround so it should work nicely with FA5 and FA6 once https://github.com/NodeBB/NodeBB/pull/10701 is merged for NodeBB 3.0 release

### CODE REVIEW

**Comment by jsumners** [comment]
Thank you for the contribution. I no longer have a NodeBB instance that I maintain, so I cannot attest to the nature of the changes. I will release them as a new semver major, but I'd like to see a post that confirms they changes are ready for release.

You indicate that there is another pending NodeBB major release. What is the timeframe on that? How would it affect this module?

**Comment by oplik0** [comment]
NodeBB has moved to actually using semver (https://nodebb.org/blog/plugin-compatibility-semver/), so major versions will be more common but shouldn't require as many changes as v2.

From the roadmap (https://nodebb.org/blog/roadmap-for-2022/) the big changes planned is the move to SASS (but less will be supported until v4 at least) and decoupling of frontend framework from NodeBB core. The second one is a bigger change for plugins then, but base Persona would inherit bootstrap3 and plugins relying on that framework should still work fine with it.

Other than these two there are currently only two "breaking" changes waiting for 3.0:
Move to FA6, which is for all practical purposes backwards compatible with FA5 and maintains the same shims for FA4 as before. It's breaking because it changes the looks of a bunch icons. It's actually a smaller update than NodeBB v1.18.0 where FA5 was added.
And moving secret from config.json to db (https://github.com/NodeBB/NodeBB/pull/10475) - which I sure hope no plugin is relying on.


When it comes to testing I have a close-to-clean test instance for it, though my workflow isn't the greatest which is why I'm making so many commits here (I'm using `npm install github:` to this branch...), but I can confirm it works with v2.1.1 I'm currently upgrading it to v2.2.0, but it should work fine too.

Also, since NodeBB 2.2.0 was just released (https://github.com/NodeBB/NodeBB/releases/tag/v2.2.0) and it contains the fix to `.fab` conflict, so if it's fine to only support it and up (and again, as now NodeBB is trying to be semver compliant there should be basically no reason not to upgrade to 2.2.0 from an earlier 2.0 or 2.1, since there are no breaking changes) - I can remove the workaround and it'll be a bit cleaner and will definitely work with FA6 later.

**Comment by jsumners** [comment]
Okay. I have converted this PR to draft status. Please change it to ready for review when it is ready.

**Comment by oplik0** [comment]
So I went back to the simple `fab fa-discord` solution without additional styles or anything, so that themes can figure that part out. As such I bumped the NodeBB compatibility to `^2.2.0` - again, I suspect this shouldn't be an issue right now since 2.2.0 contains no breaking changes when compared to 2.0.0 - so people upgrading this plugin shouldn't have a problem upgrading their installation.

I also updated the Discord API version to v10 - there are no relevant changes but v8 is already deprecated. It'll take quite a while before it's turned off (v6 is the oldest working version right now) but I don't think there is any reason not to bump it here.

**Pull request merged**
